title: JATS4R web site
baseurl: ""
url: "http://jats4r.org"
markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"